TARGET = gabutos.bin

CC = gcc
AS = nasm
LD = ld

INCLUDES = -Icpu -Imm -Idrivers -Ifs
CFLAGS = -std=gnu99 -ffreestanding -O2 -Wall -Wextra -m32 -fno-pie -fno-stack-protector $(INCLUDES)

C_SOURCES = kernel.c \
            cpu/gdt.c cpu/idt.c cpu/interrupts.c cpu/tss.c cpu/usermode.c \
            mm/pmm.c mm/vmm.c mm/heap.c \
            drivers/screen.c drivers/serial.c drivers/keyboard.c drivers/pit.c drivers/ata.c \
            fs/fs.c

ASM_SOURCES = boot/assembler.asm \
              cpu/gdt_flush.asm cpu/idt_flush.asm cpu/isr.asm cpu/usermode_asm.asm

C_OBJECTS = $(C_SOURCES:.c=.o)
ASM_OBJECTS = $(ASM_SOURCES:.asm=.o)
OBJECTS = $(ASM_OBJECTS) $(C_OBJECTS)

all: $(TARGET)

%.o: %.asm
	$(AS) -f elf32 $< -o $@

%.o: %.c
	$(CC) -c $< -o $@ $(CFLAGS)

$(TARGET): $(OBJECTS)
	$(CC) -T boot/linker.ld -o $(TARGET) -ffreestanding -O2 -nostdlib -m32 -no-pie -Wl,-z,noseparate-code -Wl,--build-id=none $(OBJECTS) -lgcc

clean:
	rm -f $(OBJECTS) $(TARGET)

run: $(TARGET)
	qemu-system-i386 -kernel $(TARGET)
